name: Scheduled Testim Tests

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  testim-test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Verify Node.js Version
      run: node -v

    - name: Check Global npm Packages
      run: npm list -g --depth=0

    - name: Install Testim CLI
      run: npm install -g testim-cli

    - name: Run Testim Tests
      env:
        TESTIM_TOKEN: ${{ secrets.TESTIM_TOKEN }}
        TESTIM_PROJECT_ID: ${{ secrets.TESTIM_PROJECT_ID }}
      run: |
        testim-cli --token "${{ secrets.TESTIM_TOKEN }}" --project "${{ secrets.TESTIM_PROJECT_ID }}" --grid "Testim-Grid" --suite "bookstore"
